// Package events provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package events

import (
	"time"

	"github.com/google/uuid"
)

// Defines values for EventSeverity.
const (
	Alert         EventSeverity = "alert"
	Critical      EventSeverity = "critical"
	Debug         EventSeverity = "debug"
	Emergency     EventSeverity = "emergency"
	Error         EventSeverity = "error"
	Informational EventSeverity = "informational"
	Warning       EventSeverity = "warning"
)

// Event Defines model for event_trackers
type Event struct {
	// ActedUpon UUID of the entity on which the event was performed.
	ActedUpon uuid.UUID `json:"acted_upon"`
	CreatedAt time.Time `json:"created_at"`
	DeletedAt time.Time `json:"deleted_at"`

	// Description A summary/receipt of event that occured.
	Description string `json:"description"`

	// EventType Is a composite key of resource name on which the operation is invoked and the action taken on the resource separated by ‘_’
	EventType string `json:"event_type"`

	// Id UUID of the event.
	Id uuid.UUID `json:"id"`

	// Metadata Contains meaningful information, specific to the type of event.
	// Structure of metadata can be different for different events.
	Metadata interface{} `json:"metadata"`

	// OperationId Each Event will have a OperationID. This field is never NULL, which is to say an operation can result in series of events, for eg: Different stages of Pattern Engine / activities of Workflow engine. Each operation (and sub-operation) will have a different operation ID.
	OperationId uuid.UUID `json:"operation_id"`

	// Severity A set of seven standard event levels.
	Severity EventSeverity `json:"severity"`

	// SystemId The system from which the request is sourced. In the case of Meshery Server,
	// the ID is meshery_instance_id of Meshery Server (which can be found in the metadata of`Connections` table).
	SystemId uuid.UUID `json:"system_id"`

	// UserId UUID of the user that initiated the event. In most cases this would be present, but not always.
	UserId uuid.UUID `json:"user_id,omitempty"`
}

// EventSeverity A set of seven standard event levels.
type EventSeverity string