version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  settings:
    staticcheck:
      checks:
        [
          "all",
          "-ST1000",
          "-ST1003",
          "-ST1005",
          "-ST1016",
          "-ST1020",
          "-ST1021",
          "-ST1022",
        ]
